# Generated by Django 5.1.1 on 2024-09-06 05:49

import add.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image', models.ImageField(upload_to='item_images')),
                ('item_resume', models.FileField(upload_to='file', validators=[add.validators.validate_file])),
            ],
        ),
    ]
